version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workbench-backend
    environment:
      - ENVIRONMENT=development
      - ALLOW_DEV_NOAUTH=true
    ports:
      - "${BACKEND_PORT-8000}:8000"
    volumes:
      - ./backend:/app
      - ./config:/app/config
      - ./agno:/app/agno
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: workbench-frontend
    environment:
      - NEXT_PUBLIC_API_ORIGIN=http://localhost:${BACKEND_PORT-8000}
    ports:
      - "${FRONTEND_PORT-3000}:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    command: sh -lc "npm install && npm run dev -- -p 3000"

