# Fly.io configuration for the Workbench UI frontend
app = "agno-frontend-staging"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.frontend"

[env]
  PORT = "3000"
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  SOPHIA_API_URL = "${SOPHIA_API_URL:-https://sophia-control-center-staging.fly.dev}"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  concurrency = { type = "connections", soft_limit = 80, hard_limit = 100 }

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[http_service.checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/"
    timeout = "10s"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
