# fly.toml app configuration file generated for agno-frontend-staging-red-leaf-9622 on 2025-09-14T23:06:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agno-frontend-staging-red-leaf-9622'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.frontend'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
