# Fly.io configuration for Sophia Intel AI Control Center
app = "sophia-control-center"
primary_region = "sjc"  # San Jose, close to CEO
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONUNBUFFERED = "1"
  AGNO_TELEMETRY = "false"
  
  # MCP Server endpoints (internal network)
  MCP_MEMORY_URL = "http://sophia-memory.internal:8081"
  MCP_FILESYSTEM_URL = "http://sophia-filesystem.internal:8082"
  MCP_GIT_URL = "http://sophia-git.internal:8084"
  MCP_VECTOR_URL = "http://sophia-vector.internal:8085"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false

# Persistent storage for backups and logs
[mounts]
  source = "sophia_data"
  destination = "/data"

# Scaling configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 512