name: Codex PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check API key presence
        shell: bash
        env:
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ -n "$CODEX_API_KEY" ] || [ -n "$OPENAI_API_KEY" ]; then
            echo "Codex API key is configured (masked)."
          else
            echo "Warning: No CODEX_API_KEY or OPENAI_API_KEY secret available." >&2
          fi

      - name: Try Codex review action
        id: codex_action
        continue-on-error: true
        uses: codex-ai/review-action@v1
        with:
          model: gpt-5-codex
        env:
          # Support either CODEX_API_KEY or OPENAI_API_KEY as a fallback
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Fallback to CLI if available
        shell: bash
        env:
          CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # If the action didn't create an output file, try local CLI if present
          if [ ! -s codex-review.md ]; then
            if [ -z "${CODEX_API_KEY}" ] && [ -n "${OPENAI_API_KEY}" ]; then
              export CODEX_API_KEY="${OPENAI_API_KEY}"
            fi
            if command -v codex >/dev/null 2>&1; then
              codex review --model gpt-5-codex --format markdown > codex-review.md || true
            fi
          fi
          # Ensure file exists to avoid failing later steps
          if [ ! -s codex-review.md ]; then
            echo "Codex review did not produce output." > codex-review.md
          fi

      - name: Comment review on PR
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const body = fs.existsSync('codex-review.md') ? fs.readFileSync('codex-review.md', 'utf8') : 'Codex review did not produce output.';
            const pr = context.payload.pull_request;
            if (!pr) {
              core.setFailed('No pull request context.');
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body
              });
            }
